set_property PACKAGE_PIN N18 [get_ports clk]
set_property PACKAGE_PIN W13 [get_ports led_g]
set_property PACKAGE_PIN W14 [get_ports led_r]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports led_g]
set_property IOSTANDARD LVCMOS33 [get_ports led_r]
